Repository Stekh/NPG-Gra-Mastermind, pull requests merged in 2024-05, with the labels that each got.

#36 fix minor spelling mistake in .gitignore
  .gitignore
Labels: fix

#35 fix .gitgnore handling of __pycache__ subdirectory
  .gitignore
Labels: fix

#40 Minor test fix
  test/test_state.py
Labels: fix

#43 add github workflow that runs automated tests using pytest
  .github/workflows/run_tests.yml
Labels: enhancement

#44 fix variable name conflict causing program to crash
  main.py
Labels: fix

#62 UI
  src/ui.py
Labels: task
